---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
locale: "fr_FR.UTF-8"
timezone: "Europe/Paris"

ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
vhosts:
  - template: standard
    vhost: "default70.dev"
    path: "{{ ansible_env.HOME }}/projects/default-7.0"
  - template: standard
    vhost: "default56.dev"
    path: "{{ ansible_env.HOME }}/projects/default-5.6"
    php: "5.6"
